In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5.6])
print(arr)
print("Shape:", arr.shape)
print("Type:", arr.dtype)

[1.  2.  3.  4.  5.6]
Shape: (5,)
Type: float64


In [11]:
arr3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr3x3)
print("Shape:", arr3x3.shape)
print("Type:", arr3x3.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Type: int64


In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Mean:", a.mean())
print("Sum:", b.sum())


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Mean: 2.0
Sum: 15


In [17]:
c = np.array([3, 6, 9])
print("Element-wise square:", c * c)
print("Sum of a 2D array:", arr3x3 + arr3x3)
print("Mean of a 2D array:", arr3x3.mean())

Element-wise square: [ 9 36 81]
Sum of a 2D array: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Mean of a 2D array: 5.0


In [19]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0,1])  # row 0, col 1
print(arr2[:,1])  # all rows, col 1
print(arr2[1,:])  # row 1, all columns
print("Last row:", arr2[2,:])
print("Last column:", arr2[:,2])

2
[2 5 8]
[4 5 6]
Last row: [7 8 9]
Last column: [3 6 9]


In [22]:
rand_arr = np.random.rand(3,3)  # 3x3 random float array
rand_int = np.random.randint(0, 10, size=(4,4))  # 4x4 random ints
print(rand_arr)
print(rand_int)

[[0.84399001 0.14689002 0.29670821]
 [0.88799658 0.72259074 0.45849834]
 [0.82615884 0.67108236 0.61536054]]
[[9 6 6 2]
 [2 1 5 0]
 [7 6 1 5]
 [1 2 4 0]]


In [30]:
rand_int_0_to_100 = np.random.randint(0, 100, size=(5,5))
print(rand_int_0_to_100)
print("Mean:", rand_int_0_to_100.mean())
print("Min:", rand_int_0_to_100.min())
print("Max:", rand_int_0_to_100.max())

[[67 22 14 84 71]
 [26 87  6 59 40]
 [ 6 67 15 56 53]
 [35  8  4 32 44]
 [36 61 43 28 31]]
Mean: 39.8
Min: 4
Max: 87


In [31]:
students = np.random.randint(50,101, size=(6,5))
def student_summary(arr):
    per_student = arr.mean(axis=1)
    per_subject = arr.mean(axis=0)
    return {"per_student": per_student, "per_subject": per_subject}

summary = student_summary(students)
print(summary)


{'per_student': array([73.4, 85. , 66.8, 83.4, 77. , 82. ]), 'per_subject': array([80.        , 79.33333333, 73.5       , 87.83333333, 69.        ])}


In [32]:
import numpy as np

# Original code
students = np.random.randint(50, 101, size=(6, 5))
def student_summary(arr):
    per_student = arr.mean(axis=1)
    per_subject = arr.mean(axis=0)
    return {"per_student": per_student, "per_subject": per_subject}

# New function to print formatted averages
def print_student_averages(names, scores):
    """
    Print formatted average scores for students and subjects.
    
    Parameters:
    names (list): List of student names (length must match number of rows in scores)
    scores (np.ndarray): 2D array of scores (rows: students, columns: subjects)
    """
    if len(names) != scores.shape[0]:
        raise ValueError("Number of names must match number of students (rows).")
    
    # Get averages from student_summary
    summary = student_summary(scores)
    per_student = summary["per_student"]
    per_subject = summary["per_subject"]
    
    # Print per-student averages
    print("Student Averages:")
    for i, (name, avg) in enumerate(zip(names, per_student)):
        print(f"{name}: {avg:.2f}")
    
    # Print per-subject averages
    print("\nSubject Averages:")
    for i, avg in enumerate(per_subject):
        print(f"Subject {i + 1}: {avg:.2f}")

# Example usage
student_names = ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank"]
print_student_averages(student_names, students)

Student Averages:
Alice: 73.60
Bob: 65.60
Charlie: 70.40
Diana: 79.40
Eve: 75.00
Frank: 74.60

Subject Averages:
Subject 1: 77.00
Subject 2: 78.83
Subject 3: 70.33
Subject 4: 75.17
Subject 5: 64.17
